
```{r,warning=FALSE,message=FALSE,echo=FALSE}
  if(is.numeric(dt.fr[,covars[i]])){
    
    vartable<-data.frame(Variable=colnames(dt.fr)[covars[i]],
                    Mean=round(mean(dt.fr[,covars[i]],na.rm=TRUE),2),
                    Median=round(median(dt.fr[,covars[i]],na.rm=TRUE),1),
               Minimum=min(dt.fr[,covars[i]],na.rm=TRUE),Maximum=max(dt.fr[,covars[i]],na.rm=TRUE),
               "Standard Deviation"=round(sd(dt.fr[,covars[i]],na.rm=TRUE),2))
    

    
   p1<- ggplot(data=dataset,aes_string(x=colnames(dt.fr)[covars[i]]))+
      geom_histogram(col="black",fill=alpha("red",0.5),bins=20)+
     ggtitle(paste("Histogram of",colnames(dt.fr)[covars[i]]))+ylab("Frequency")+
     scale_y_continuous(sec.axis = sec_axis(~./nrow(dataset),labels=scales::percent,
                                                   name="Percentage"))

    
  }
    if(class(dt.fr[,covars[i]])=="Date"){
    
    vartable<-data.frame(Variable=colnames(dt.fr)[covars[i]],"Median Date"=median(dt.fr[,covars[i]],na.rm=TRUE),
               "Earliest Date"=min(dt.fr[,covars[i]],na.rm=TRUE),"Final Date"=max(dt.fr[,covars[i]],na.rm=TRUE))
    

    
   p1<- ggplot(data=dataset,aes_string(x=colnames(dt.fr)[covars[i]]))+
      geom_histogram(col="black",fill=alpha("blue",0.5))+
     ggtitle(paste("Histogram of",colnames(dt.fr)[covars[i]]))+ylab("Frequency")+
scale_x_date(date_breaks = "2 days", date_minor_breaks = "1 day", date_labels = "%d-%b")+
     scale_y_continuous(sec.axis = sec_axis(~./nrow(dataset),labels=scales::percent,
                                                   name="Percentage"))
}
    if(is.character(dt.fr[,covars[i]])|is.factor(dt.fr[,covars[i]])){
    
      vartable<-data.frame(table(dt.fr[,covars[i]]))
colnames(vartable)<-c(colnames(dt.fr)[covars[i]],"Frequency")
 vartable<-vartable %>%
  mutate("% of Respondents"=percent(Frequency/sum(Frequency),1)) 

   p1<- ggplot(data=dataset,aes_string(x=colnames(dt.fr)[covars[i]]))+
      geom_bar(col="black",fill=alpha("forestgreen",0.5))+coord_flip()+
     ggtitle(paste("Barchart of",colnames(dt.fr)[covars[i]]))+ylab("Frequency")+
     scale_y_continuous(sec.axis = sec_axis(~./sum(vartable$Frequency),labels=scales::percent,
                                                   name="Percentage"))

    }

```

```{r}
vartable %>% kable(caption=paste("Table 2.",i," Summary of ",colnames(dt.fr)[covars[i]],sep=""))
```

```{r}
plot(p1)
```
