
```{r,warning=FALSE,message=FALSE,echo=FALSE}
   gsplit=TRUE

dt.fr$miss_tmp<-factor(is.na(dt.fr[covars[i]]),levels=c(FALSE,TRUE),labels=c("Complete","Missing"))

misstable<-data.frame(table(dt.fr$miss_tmp))
misstable$Percent<-percent(misstable$Freq/sum(misstable$Freq))
colnames(misstable)[1]<-colnames(dt.fr)[covars[i]]

if(covars[i]==gender|length(gender)==0){
  gsplit=FALSE
}

 if(is.numeric(dt.fr[,covars[i]])){
      vartable<-data.frame(Variable=colnames(dt.fr)[covars[i]],
                    Mean=round(mean(dt.fr[,covars[i]],na.rm=TRUE),2),
                    Median=round(median(dt.fr[,covars[i]],na.rm=TRUE),1),
               Minimum=min(dt.fr[,covars[i]],na.rm=TRUE),Maximum=max(dt.fr[,covars[i]],na.rm=TRUE),
               "Standard Deviation"=round(sd(dt.fr[,covars[i]],na.rm=TRUE),2),check.names = FALSE)
    
if(gsplit==FALSE){    
 

   p1<- ggplot(data=dataset,aes_string(x=colnames(dt.fr)[covars[i]]))+
      geom_histogram(col="black",fill=alpha("red",0.5),bins=20)+
     ggtitle(paste("Histogram of",colnames(dt.fr)[covars[i]]))+ylab("Frequency")+
     scale_y_continuous(sec.axis = sec_axis(~./nrow(dataset),labels=scales::percent,
                                                   name="Percentage"))
}
    else{
      dt.fr$gender<-factor(dt.fr[,gender])
              vartable1<-data.frame(Variable=colnames(dt.fr)[covars[i]],gender=levels(dt.fr[,gender]),
                    Mean=round(tapply(dt.fr[,covars[i]],dt.fr[,gender],mean,na.rm=TRUE),2),
                    Median=round(tapply(dt.fr[,covars[i]],dt.fr[,gender],median,na.rm=TRUE),2),
               Minimum=round(tapply(dt.fr[,covars[i]],dt.fr[,gender],min,na.rm=TRUE),2),
               Maximum=round(tapply(dt.fr[,covars[i]],dt.fr[,gender],max,na.rm=TRUE),2),
               "Standard Deviation"=round(tapply(dt.fr[,covars[i]],dt.fr[,gender],sd,na.rm=TRUE),2),check.names = FALSE)
    

    vartable$gender<-"Overall"
vartable<-merge(vartable1,vartable,all=TRUE)

   p1<- ggplot(data=dataset[is.na(dataset$gender)==FALSE,],aes_string(x=colnames(dt.fr)[covars[i]]))+facet_wrap(~gender)+
      geom_histogram(col="black",fill=alpha("red",0.5),bins=20)+
     ggtitle(paste("Histogram of",colnames(dt.fr)[covars[i]]))+ylab("Frequency")+
     scale_y_continuous(sec.axis = sec_axis(~./nrow(dataset),labels=scales::percent,
                                                   name="Percentage"))  
    }

    
  }
    if(class(dt.fr[,covars[i]])=="Date"){
    
      
       vartable<-data.frame(Variable=colnames(dt.fr)[covars[i]],
                                 "Median Date"=as.Date(median(dt.fr[,covars[i]],na.rm=TRUE)),
               "Earliest Date"=as.Date(min(dt.fr[,covars[i]],na.rm=TRUE)),
               "Final Date"=as.Date(max(dt.fr[,covars[i]],na.rm=TRUE)),check.names = FALSE)
      
      if(gsplit==TRUE){  
              dt.fr$gender<-factor(dt.fr[,gender])
    vartable1<-data.frame(Variable=colnames(dt.fr)[covars[i]],gender=levels(dt.fr[,gender]),
                         "Median Date"=as.Date(tapply(dt.fr[,covars[i]],dt.fr[,gender],median,na.rm=TRUE), 
                                               origin = "1970-01-01"),
               "Earliest Date"=as.Date(tapply(dt.fr[,covars[i]],dt.fr[,gender],min,na.rm=TRUE), origin = "1970-01-01"),"Final Date"=as.Date(tapply(dt.fr[,covars[i]],dt.fr[,gender],max,na.rm=TRUE), origin = "1970-01-01"),check.names = FALSE)
    
vartable$gender<-"Overall"
vartable<-merge(vartable1,vartable,all=TRUE)
    
   p1<- ggplot(data=dataset[is.na(dataset$gender)==FALSE,],aes_string(x=colnames(dt.fr)[covars[i]]))+
     facet_wrap(~gender)+
      geom_histogram(col="black",fill=alpha("blue",0.5))+
     ggtitle(paste("Histogram of",colnames(dt.fr)[covars[i]]))+ylab("Frequency")+
scale_x_date(date_labels = "%d-%b")+
     scale_y_continuous(sec.axis = sec_axis(~./nrow(dataset),labels=scales::percent,
                                                   name="Percentage"))+
     theme(axis.text.x = element_text(angle=90))
      }
      else{
           
    
   p1<- ggplot(data=dataset,aes_string(x=colnames(dt.fr)[covars[i]]))+
      geom_histogram(col="black",fill=alpha("blue",0.5))+
     ggtitle(paste("Histogram of",colnames(dt.fr)[covars[i]]))+ylab("Frequency")+
scale_x_date(date_labels = "%d-%b")+
     scale_y_continuous(sec.axis = sec_axis(~./nrow(dataset),labels=scales::percent,
                                                   name="Percentage"))
      }
}
    if(is.character(dt.fr[,covars[i]])|is.factor(dt.fr[,covars[i]])){
    
      vartable<-data.frame(table(dt.fr[,covars[i]]))
colnames(vartable)<-c(colnames(dt.fr)[covars[i]],"Frequency")
 vartable<-vartable %>%
  mutate("% of Respondents"=percent(Frequency/sum(Frequency),1)) 
      
      dt.fr$tmp<-factor(dt.fr[,colnames(dt.fr)[covars[i]]],
                        levels=rev(sort(unique(dt.fr[,colnames(dt.fr)[covars[i]]]))))
        if(gsplit==TRUE){  
          
          vartable1<-data.frame(table(dt.fr[,covars[i]],dt.fr[,gender]))

 vartable1<-vartable1 %>% group_by(Var2) %>% mutate(per=Freq/sum(Freq)) %>%
   ungroup() %>%  mutate(per=percent(per))%>% select(Var1,Var2,per) %>%   spread(Var2,per)
colnames(vartable1)[2:3]<-paste("% Within",colnames(vartable1)[2:3])
vartable<-cbind(vartable,vartable1[,2:3])



   p1<- ggplot(data=dt.fr[is.na(dt.fr[,gender])==FALSE,],aes_string(x="tmp",fill=colnames(dt.fr)[gender]))+
      geom_bar(col="black")+coord_flip()+
     ggtitle(paste("Barchart of",colnames(dt.fr)[covars[i]]))+ylab("Frequency")+
     scale_y_continuous(name="Count")+xlab(colnames(dt.fr)[covars[i]])
 
        }
      else{
   p1<- ggplot(data=dt.fr,aes_string(x="tmp"))+
      geom_bar(col="black",fill=alpha("forestgreen",0.5))+coord_flip()+
     ggtitle(paste("Barchart of",colnames(dt.fr)[covars[i]]))+ylab("Frequency")+
     scale_y_continuous(sec.axis = sec_axis(~./sum(vartable$Frequency),labels=scales::percent,
                                                   name="Percentage"))+xlab(colnames(dt.fr)[covars[i]])

      }
    }


```



**`r colnames(dt.fr)[covars[i]]` **

```{r}
kable(misstable,caption=paste0("Table 3.",i,".1"," Missing Values in ",colnames(dt.fr)[covars[i]]))
```



```{r}
vartable %>% kable(caption=paste0("Table 3.",i,".2"," Summary statistics for ",colnames(dt.fr)[covars[i]]))
```

*Figure `r paste("3.",i,sep="")`*
```{r}
plot(p1)
```

```{r}
exclusionmessage<-""

if(stoplist[i]==1){
exclusionmessage<-paste0("NOTE: The variable ",colnames(dt.fr)[covars[i]]," was flagged to be excluded as a possible covariate for the statistical modelling. This was because not all of the ",options," were present in all of the different ",colnames(dt.fr)[covars[i]]," groups. To be able to consider the effect of this variable, consider manually grouping some of the levels together, where appropriate.")
}
if(stoplist[i]==2){
exclusionmessage<-paste0("NOTE: The variable ",colnames(dt.fr)[covars[i]]," was flagged to be excluded as a possible covariate for the statistical modelling. This was because of an unknown error.")
}
if(stoplist[i]==4){
exclusionmessage<-paste0("NOTE: The variable ",colnames(dt.fr)[covars[i]]," was flagged to be excluded as a possible covariate for the statistical modelling. This was because the amount of missing data within this variable exceeded the allowable maximum threshold, which has been set at ",percent(missper))
}
```

`r exclusionmessage`
